branch-defaults:
  default:
    environment: sticker-dev
environment-defaults:
  sticker-dev:
    branch: null
    repository: null
global:
  application_name: stickerEconomy
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.6.5
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
