# Generated by Django 2.0.2 on 2018-03-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
