# Generated by Django 2.0.2 on 2018-03-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_sticker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.ImageField(upload_to='med'),
        ),
    ]
