# Generated by Django 2.0.2 on 2018-03-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_auto_20180306_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
