# Generated by Django 2.0.2 on 2018-03-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0006_traderequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderequest',
            name='requested_sticker',
        ),
        migrations.DeleteModel(
            name='TradeRequest',
        ),
    ]
