# Generated by Django 2.0.2 on 2018-03-13 14:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('economy', '0009_auto_20180309_1201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sticker',
            unique_together={('owner', 'title', 'image')},
        ),
    ]
