# Generated by Django 2.0.2 on 2018-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0010_auto_20180313_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
