# Generated by Django 2.0.3 on 2018-03-21 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('economy', '0016_auto_20180316_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
