# Generated by Django 2.0.3 on 2018-03-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0018_auto_20180321_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traderequest',
            old_name='asked_completed',
            new_name='given_completed',
        ),
        migrations.RenameField(
            model_name='traderequest',
            old_name='asker_completed',
            new_name='requested_completed',
        ),
    ]
