# Generated by Django 2.0.3 on 2018-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0019_auto_20180321_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
