# Generated by Django 2.0.3 on 2018-03-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0021_message_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_type',
            new_name='msg_type',
        ),
    ]
