# Generated by Django 2.0.2 on 2018-03-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0011_auto_20180313_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
