# Generated by Django 2.0.2 on 2018-03-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0012_traderequest_accepted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sticker',
            unique_together=set(),
        ),
    ]
