# Generated by Django 2.0.3 on 2018-03-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0013_auto_20180313_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('staff_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
