# Generated by Django 2.0.3 on 2018-03-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0017_traderequest_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='asked_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='asker_completed',
            field=models.BooleanField(default=False),
        ),
    ]
